version: "3.1"
recipe: default.v1
language: it
pipeline:
- name: SpacyNLP
  model: "it_core_news_md"
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3

policies:
- name: RulePolicy
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20241208-181213-dark-slate
